### ISSUE TITLE
knife ec2 create for windows giving error

### ISSUE THREAD

**Issue by sujan46** [chef/knife-ec2#449]
When I run a knife ec2 create it creates the Instance, But I am having issue while bootstarping the instance.

command ran
`knife ec2 server create -N win_node_2 -I ami-2827f548 -f t2.micro -x 'Administrator' -P 'my_password' --ssh-key win --winrm-transport ssl --winrm-ssl-verify-mode verify_none --security-group-ids sg-6af16213 -VV
`

The issue is Failing authentication
`ERROR: Failed to authenticate to ec2-xx-xxx-xx-xxx.us-xxxx-x.compute.amazonaws.com as Administrator
Response: WinRM::WinRMAuthorizationError
Hint: Make sure to prefix domain usernames with the correct domain name.
Hint: Local user names should be prefixed with computer name or IP address.
EXAMPLE: my_domain\user_namer`

Please Help

Thank you

**Comment by sujan46** [comment]
The issue is resolved. It turned I was giving the wrong username

`knife ec2 server create -N win_node_2 -I ami-2827f548 -f t2.micro -x './username' -P 'my_password' --ssh-key win --winrm-transport ssl --winrm-ssl-verify-mode verify_none --security-group-ids sg-6af16213 -VV `

**Comment by sernapallyanurag** [comment]
I am facing same issue. I didn't get what was wrong in your username in first post. How do you get a right username. I am little confused here. Can you help me out?

**Comment by sujan46** [comment]
@sernapallyanurag 

username which you will give in ec2 command will create that new user under the Administrator group. It is just like creating new user in windows.

**Comment by sernapallyanurag** [comment]
I have tried using the command u mentioned above ``.\username`` but I am still getting this error while bootstrapping. Create is doing fine.

**Comment by sujan46** [comment]
Can you please post the command you are trying

**Comment by sernapallyanurag** [comment]
knife ec2 server create -N windowstest -I ami-2843e54b -f t2.micro --bootstrap-protocol winrm --winrm-user .\windowsuser --winrm-password admin@123 --region ap-southeast-1 --availability-zone ap-southeast-1b --subnet subnet-0707est23 --winrm-transport ssl --security-group-ids sg-abc875at
